version: '3.5'

networks:
  nest-graph:
volumes:
    postgres:
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: nest-graph
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin123$%^
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - nest-graph
    restart: always

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    # logging:
    #   driver: 'none'
    networks:
      - nest-graph

  api:
    container_name: api-server
    build:
      context: ./nest-graph
    ports:
      - 9000:9000
    networks:
      - nest-graph
    depends_on:
      - postgres
      - kafka
    volumes:
      - ./nest-graph/src/:/app/src/
    
  microservice:
    container_name: micro-service
    build:
      context: ./nest-micro-service
    networks:
      - nest-graph
    depends_on:
      - postgres
      - kafka
    volumes:
      - ./nest-micro-service/src/:/app/src/
  
  
